@startuml c2
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
LAYOUT_WITH_LEGEND()
'Ald+D to preview
title C2 - Container diagram for Orcha

Person(serverAdm, "Proxmox Server Administrator", "A Proxmox server administrator who manages multiple containers and/or game servers.")

System_Boundary(c1, "Orcha") {
    Container(web_app, "Web Application", "x", "Not Yet Implemented")
    Container(orcha, "API Application", "GoLang", "Provides Proxmox Orchestration functionality via API")
    Container(narwhal, "Narwhal", "GoLang", "Provides an abstraction layer for managing game servers running in Proxmox containers")
}

System_Ext(linux_gsm, "LinuxGSM", "Command-line tool for deployment and management of Linux dedicated game servers.")
System_Ext(proxmox_server, "Proxmox server", "A Proxmox server hosting multiple containers and game servers.")

Rel(serverAdm, web_app, "Uses", "HTTPS")
Rel(web_app, orcha, "Uses", "x")

Rel_Neighbor(orcha, proxmox_server, "Uses", "HTTPS")
Rel(orcha, narwhal, "Uses", "ssh")
Rel(orcha, linux_gsm, "Uses", "ssh")
@enduml